addSbtPlugin("org.scalameta"    % "sbt-scalafmt"              % "2.5.1")
addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.3.1")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"               % "0.6.4")
addSbtPlugin("org.typelevel"    % "sbt-tpolecat"              % "0.5.0")
addSbtPlugin("com.github.sbt"   % "sbt-ci-release"            % "1.5.12")
